version: '3.5'
services:
  Api.Service:
   #image: ${DOCKER_REGISTRY-}dockerapiazure:v1
   build:
    context: ./DockerApiAzure
    dockerfile: Dockerfile
   environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:80
   ports:
    - "80:80"